### ISSUE TITLE
App does not block keyboard while e.g. in facebook chat

### ISSUE THREAD

**Issue by MarcinGie** [quepas/Cat-Blocker#2]
There is a bug that triggers the app(correctly, when user presses 4 keys simulatneously), but it runs in background and does not block any interaction. It is easy to reproduce, however I've provided a screen to show an issue.
![catblockerbug](https://cloud.githubusercontent.com/assets/6605962/7031069/5413c654-dd69-11e4-8694-c5da17d5844d.png)

**Comment by quepas** [comment]
I manage to reproduce this behaviour, even in case when other window is currently active. I also found  solution for this problem: to force app window to be always on top. Commit is underway!

**Comment by quepas** [comment]
Problem fixed.
